name: baadd
channels:
  - pytorch
  - defaults
dependencies:
  - conda=23.3.1
  - python=3.9.*
  - pip=23.0.1
  - cudatoolkit=11.3.1
  - pip:
    - torch==1.13.1
    - torchvision==0.14.1
    - adversarial-robustness-toolbox
    - pandas
    - matplotlib
    - pyyaml